==34216== Memcheck, a memory error detector
==34216== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==34216== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==34216== Command: ./BuildingBlocks_test
==34216== 
==34216== 
==34216== HEAP SUMMARY:
==34216==     in use at exit: 2,160 bytes in 84 blocks
==34216==   total heap usage: 1,547 allocs, 1,463 frees, 164,761 bytes allocated
==34216== 
==34216== 88 (24 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 25 of 40
==34216==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==34216==    by 0x127BA3: Node::Node(Mat*) (Node.cpp:7)
==34216==    by 0x11FF82: NodeOperations_node_addition_Test::TestBody() (NodeSanityTest.cpp:36)
==34216==    by 0x169560: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x161684: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x13C11B: testing::Test::Run() (gtest.cc:2684)
==34216==    by 0x13CC36: testing::TestInfo::Run() (gtest.cc:2864)
==34216==    by 0x13D574: testing::TestSuite::Run() (gtest.cc:3023)
==34216==    by 0x14D922: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5885)
==34216==    by 0x16AA72: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x1628A0: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x14BF44: testing::UnitTest::Run() (gtest.cc:5459)
==34216== 
==34216== 88 (24 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 26 of 40
==34216==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==34216==    by 0x127BA3: Node::Node(Mat*) (Node.cpp:7)
==34216==    by 0x11FFF6: NodeOperations_node_addition_Test::TestBody() (NodeSanityTest.cpp:39)
==34216==    by 0x169560: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x161684: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x13C11B: testing::Test::Run() (gtest.cc:2684)
==34216==    by 0x13CC36: testing::TestInfo::Run() (gtest.cc:2864)
==34216==    by 0x13D574: testing::TestSuite::Run() (gtest.cc:3023)
==34216==    by 0x14D922: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5885)
==34216==    by 0x16AA72: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x1628A0: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x14BF44: testing::UnitTest::Run() (gtest.cc:5459)
==34216== 
==34216== 88 (24 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 27 of 40
==34216==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==34216==    by 0x127BA3: Node::Node(Mat*) (Node.cpp:7)
==34216==    by 0x127DAF: Node::operator+(Node&) (Node.cpp:14)
==34216==    by 0x12001A: NodeOperations_node_addition_Test::TestBody() (NodeSanityTest.cpp:41)
==34216==    by 0x169560: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x161684: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x13C11B: testing::Test::Run() (gtest.cc:2684)
==34216==    by 0x13CC36: testing::TestInfo::Run() (gtest.cc:2864)
==34216==    by 0x13D574: testing::TestSuite::Run() (gtest.cc:3023)
==34216==    by 0x14D922: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5885)
==34216==    by 0x16AA72: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x1628A0: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2645)
==34216== 
==34216== 120 (24 direct, 96 indirect) bytes in 1 blocks are definitely lost in loss record 31 of 40
==34216==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==34216==    by 0x127BA3: Node::Node(Mat*) (Node.cpp:7)
==34216==    by 0x128109: Node::operator*(Node&) (Node.cpp:29)
==34216==    by 0x120DD3: NodeOperations_node_multiplication_Test::TestBody() (NodeSanityTest.cpp:80)
==34216==    by 0x169560: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x161684: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x13C11B: testing::Test::Run() (gtest.cc:2684)
==34216==    by 0x13CC36: testing::TestInfo::Run() (gtest.cc:2864)
==34216==    by 0x13D574: testing::TestSuite::Run() (gtest.cc:3023)
==34216==    by 0x14D922: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5885)
==34216==    by 0x16AA72: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x1628A0: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2645)
==34216== 
==34216== 120 (24 direct, 96 indirect) bytes in 1 blocks are definitely lost in loss record 32 of 40
==34216==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==34216==    by 0x121032: NodeOperations_node_multiplication_Test::TestBody() (NodeSanityTest.cpp:87)
==34216==    by 0x169560: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x161684: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x13C11B: testing::Test::Run() (gtest.cc:2684)
==34216==    by 0x13CC36: testing::TestInfo::Run() (gtest.cc:2864)
==34216==    by 0x13D574: testing::TestSuite::Run() (gtest.cc:3023)
==34216==    by 0x14D922: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5885)
==34216==    by 0x16AA72: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x1628A0: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x14BF44: testing::UnitTest::Run() (gtest.cc:5459)
==34216==    by 0x118BE5: RUN_ALL_TESTS() (gtest.h:2304)
==34216== 
==34216== 144 (24 direct, 120 indirect) bytes in 1 blocks are definitely lost in loss record 33 of 40
==34216==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==34216==    by 0x127BA3: Node::Node(Mat*) (Node.cpp:7)
==34216==    by 0x120D38: NodeOperations_node_multiplication_Test::TestBody() (NodeSanityTest.cpp:75)
==34216==    by 0x169560: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x161684: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x13C11B: testing::Test::Run() (gtest.cc:2684)
==34216==    by 0x13CC36: testing::TestInfo::Run() (gtest.cc:2864)
==34216==    by 0x13D574: testing::TestSuite::Run() (gtest.cc:3023)
==34216==    by 0x14D922: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5885)
==34216==    by 0x16AA72: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x1628A0: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x14BF44: testing::UnitTest::Run() (gtest.cc:5459)
==34216== 
==34216== 152 (24 direct, 128 indirect) bytes in 1 blocks are definitely lost in loss record 34 of 40
==34216==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==34216==    by 0x127BA3: Node::Node(Mat*) (Node.cpp:7)
==34216==    by 0x120DAC: NodeOperations_node_multiplication_Test::TestBody() (NodeSanityTest.cpp:78)
==34216==    by 0x169560: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x161684: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x13C11B: testing::Test::Run() (gtest.cc:2684)
==34216==    by 0x13CC36: testing::TestInfo::Run() (gtest.cc:2864)
==34216==    by 0x13D574: testing::TestSuite::Run() (gtest.cc:3023)
==34216==    by 0x14D922: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5885)
==34216==    by 0x16AA72: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x1628A0: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x14BF44: testing::UnitTest::Run() (gtest.cc:5459)
==34216== 
==34216== 224 (48 direct, 176 indirect) bytes in 1 blocks are definitely lost in loss record 35 of 40
==34216==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==34216==    by 0x11F542: NodeSetup_testing_node_sanity_Test::TestBody() (NodeSanityTest.cpp:13)
==34216==    by 0x169560: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x161684: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x13C11B: testing::Test::Run() (gtest.cc:2684)
==34216==    by 0x13CC36: testing::TestInfo::Run() (gtest.cc:2864)
==34216==    by 0x13D574: testing::TestSuite::Run() (gtest.cc:3023)
==34216==    by 0x14D922: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5885)
==34216==    by 0x16AA72: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x1628A0: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x14BF44: testing::UnitTest::Run() (gtest.cc:5459)
==34216==    by 0x118BE5: RUN_ALL_TESTS() (gtest.h:2304)
==34216== 
==34216== 224 (48 direct, 176 indirect) bytes in 1 blocks are definitely lost in loss record 36 of 40
==34216==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==34216==    by 0x11FF6D: NodeOperations_node_addition_Test::TestBody() (NodeSanityTest.cpp:36)
==34216==    by 0x169560: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x161684: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x13C11B: testing::Test::Run() (gtest.cc:2684)
==34216==    by 0x13CC36: testing::TestInfo::Run() (gtest.cc:2864)
==34216==    by 0x13D574: testing::TestSuite::Run() (gtest.cc:3023)
==34216==    by 0x14D922: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5885)
==34216==    by 0x16AA72: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x1628A0: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x14BF44: testing::UnitTest::Run() (gtest.cc:5459)
==34216==    by 0x118BE5: RUN_ALL_TESTS() (gtest.h:2304)
==34216== 
==34216== 224 (48 direct, 176 indirect) bytes in 1 blocks are definitely lost in loss record 37 of 40
==34216==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==34216==    by 0x11FFE1: NodeOperations_node_addition_Test::TestBody() (NodeSanityTest.cpp:39)
==34216==    by 0x169560: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x161684: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x13C11B: testing::Test::Run() (gtest.cc:2684)
==34216==    by 0x13CC36: testing::TestInfo::Run() (gtest.cc:2864)
==34216==    by 0x13D574: testing::TestSuite::Run() (gtest.cc:3023)
==34216==    by 0x14D922: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5885)
==34216==    by 0x16AA72: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x1628A0: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x14BF44: testing::UnitTest::Run() (gtest.cc:5459)
==34216==    by 0x118BE5: RUN_ALL_TESTS() (gtest.h:2304)
==34216== 
==34216== 336 (48 direct, 288 indirect) bytes in 1 blocks are definitely lost in loss record 38 of 40
==34216==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==34216==    by 0x120D23: NodeOperations_node_multiplication_Test::TestBody() (NodeSanityTest.cpp:75)
==34216==    by 0x169560: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x161684: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x13C11B: testing::Test::Run() (gtest.cc:2684)
==34216==    by 0x13CC36: testing::TestInfo::Run() (gtest.cc:2864)
==34216==    by 0x13D574: testing::TestSuite::Run() (gtest.cc:3023)
==34216==    by 0x14D922: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5885)
==34216==    by 0x16AA72: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x1628A0: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x14BF44: testing::UnitTest::Run() (gtest.cc:5459)
==34216==    by 0x118BE5: RUN_ALL_TESTS() (gtest.h:2304)
==34216== 
==34216== 352 (48 direct, 304 indirect) bytes in 1 blocks are definitely lost in loss record 39 of 40
==34216==    at 0x4849013: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==34216==    by 0x120D97: NodeOperations_node_multiplication_Test::TestBody() (NodeSanityTest.cpp:78)
==34216==    by 0x169560: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x161684: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x13C11B: testing::Test::Run() (gtest.cc:2684)
==34216==    by 0x13CC36: testing::TestInfo::Run() (gtest.cc:2864)
==34216==    by 0x13D574: testing::TestSuite::Run() (gtest.cc:3023)
==34216==    by 0x14D922: testing::internal::UnitTestImpl::RunAllTests() (gtest.cc:5885)
==34216==    by 0x16AA72: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2609)
==34216==    by 0x1628A0: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest.cc:2645)
==34216==    by 0x14BF44: testing::UnitTest::Run() (gtest.cc:5459)
==34216==    by 0x118BE5: RUN_ALL_TESTS() (gtest.h:2304)
==34216== 
==34216== LEAK SUMMARY:
==34216==    definitely lost: 408 bytes in 12 blocks
==34216==    indirectly lost: 1,752 bytes in 72 blocks
==34216==      possibly lost: 0 bytes in 0 blocks
==34216==    still reachable: 0 bytes in 0 blocks
==34216==         suppressed: 0 bytes in 0 blocks
==34216== 
==34216== For lists of detected and suppressed errors, rerun with: -s
==34216== ERROR SUMMARY: 12 errors from 12 contexts (suppressed: 0 from 0)
